service: serverless-nextjs-styled-components

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2

plugins:
  - serverless-nextjs-plugin
  - serverless-domain-manager
  - serverless-offline

custom:
  serverless-nextjs:
    nextConfigDir: "./"
    # assetsBucketName: "austincc.xyz.serverless"

  customDomain:
    domainName: dev.austincc.xyz
    stage: dev
    # basePath: ""
    certificateName: "*.austincc.xyz"
    createRoute53Record: true
    # endpointType: "regional" # default is edge

package:
  exclude:
    - ./**
